capture_date: 2013:01:25 12:01:26Z
capture_agent: NjP
scanner_user: Princeton University Library Digital Initiatives
scanner_make: Leaf
scanner_model: Leaf Aptus-II 12(LI301708   )/Schneider Lens Control
