capture_date: 2012:04:09 11:33:45Z
capture_agent: NjP
scanner_user: Princeton University Library Digital Initiatives
scanner_make: Leaf
scanner_model: Leaf Aptus-II 12(LI301708   )/Schneider Lens Control
