capture_date: 2012:08:06 14:43:02Z
capture_agent: NjP
scanner_user: Princeton University Library Digital Initiatives
scanner_make: Leaf
scanner_model: Leaf Aptus-II 12(LI301737   )/Schneider Lens Control
